[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"

# GitHub Actions 部署配置
[context.production]
  command = "echo 'Deployed via GitHub Actions'"

[context.deploy-preview]
  command = "echo 'Deploy preview'"
